# Generated by Django 4.2 on 2026-02-06 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brewery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Processo')),
                ('categoria', models.CharField(choices=[('producao', 'Produção'), ('limpeza', 'Limpeza'), ('envase', 'Envase'), ('qualidade', 'Qualidade')], max_length=50, verbose_name='Categoria')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cervejaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='brewery.brewery', verbose_name='Cervejaria')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'ordering': ['-criado_em'],
                'unique_together': {('cervejaria', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='EtapaProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Etapa')),
                ('ordem', models.PositiveIntegerField(verbose_name='Ordem')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='processes.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Etapa do Processo',
                'verbose_name_plural': 'Etapas do Processo',
                'ordering': ['ordem'],
                'unique_together': {('processo', 'ordem')},
            },
        ),
    ]
