# Generated by Django 4.2 on 2026-02-06 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brewery', '0001_initial'),
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutacaoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('nao_iniciada', 'Não Iniciada'), ('em_progresso', 'Em Progresso'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='nao_iniciada', max_length=20, verbose_name='Status')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações Gerais')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='processes.processo', verbose_name='Processo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Iniciou')),
            ],
            options={
                'verbose_name': 'Execução de Processo',
                'verbose_name_plural': 'Execuções de Processo',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PontoCriticoHACCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('temperatura', 'Temperatura'), ('ph', 'pH'), ('tempo', 'Tempo'), ('pressao', 'Pressão'), ('concentracao', 'Concentração'), ('outro', 'Outro')], max_length=50, verbose_name='Tipo de Ponto Crítico')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Ponto Crítico')),
                ('limite_minimo', models.FloatField(verbose_name='Limite Mínimo')),
                ('limite_maximo', models.FloatField(verbose_name='Limite Máximo')),
                ('unidade', models.CharField(max_length=20, verbose_name='Unidade (°C, pH, min, etc)')),
                ('acao_preventiva', models.TextField(verbose_name='Ação Preventiva')),
                ('acao_corretiva', models.TextField(verbose_name='Ação Corretiva')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_criticos', to='processes.etapaprocesso', verbose_name='Etapa')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_criticos', to='processes.processo', verbose_name='Processo')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Ponto Crítico HACCP',
                'verbose_name_plural': 'Pontos Críticos HACCP',
                'ordering': ['etapa__ordem'],
            },
        ),
        migrations.CreateModel(
            name='RegistroHACCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_medido', models.FloatField(verbose_name='Valor Medido')),
                ('conforme', models.BooleanField(verbose_name='Conforme Limite?')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora do Registro')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_haccp', to='processes.executacaoprocesso', verbose_name='Execução')),
                ('ponto_critico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='processes.pontocriticohaccp', verbose_name='Ponto Crítico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Registrou')),
            ],
            options={
                'verbose_name': 'Registro HACCP',
                'verbose_name_plural': 'Registros HACCP',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='NaoConformidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da NC')),
                ('descricao', models.TextField(verbose_name='Descrição da Não Conformidade')),
                ('severidade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20, verbose_name='Severidade')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_analise', 'Em Análise'), ('em_correcao', 'Em Correção'), ('fechada', 'Fechada')], default='aberta', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('cervejaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nao_conformidades', to='brewery.brewery', verbose_name='Cervejaria')),
                ('execucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nc_geradas', to='processes.executacaoprocesso', verbose_name='Execução Associada')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ncs_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Criou')),
            ],
            options={
                'verbose_name': 'Não Conformidade',
                'verbose_name_plural': 'Não Conformidades',
                'ordering': ['-data_criacao', '-severidade'],
            },
        ),
        migrations.CreateModel(
            name='KPIExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Início do Período')),
                ('data_fim', models.DateField(verbose_name='Fim do Período')),
                ('total_processos_executados', models.IntegerField(default=0, verbose_name='Total de Processos Executados')),
                ('processos_sem_nc', models.IntegerField(default=0, verbose_name='Processos sem Não Conformidade')),
                ('taxa_conformidade', models.FloatField(default=0, verbose_name='Taxa de Conformidade (%)')),
                ('registros_haccp_conformes', models.IntegerField(default=0, verbose_name='Registros HACCP Conformes')),
                ('registros_haccp_nao_conformes', models.IntegerField(default=0, verbose_name='Registros HACCP Não Conformes')),
                ('total_ncs', models.IntegerField(default=0, verbose_name='Total de NCs Abertas')),
                ('ncs_fechadas', models.IntegerField(default=0, verbose_name='NCs Fechadas')),
                ('ncs_criticas', models.IntegerField(default=0, verbose_name='NCs Críticas Ativas')),
                ('total_capasscii', models.IntegerField(default=0, verbose_name='Total de CAPAs')),
                ('capas_concluidas', models.IntegerField(default=0, verbose_name='CAPAs Concluídas')),
                ('receita_bruta', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Receita Bruta')),
                ('custos_produção', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Custos de Produção')),
                ('custos_operacionais', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Custos Operacionais')),
                ('lucro_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Lucro Bruto')),
                ('lucro_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Lucro Líquido')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cervejaria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kpi', to='brewery.brewery', verbose_name='Cervejaria')),
            ],
            options={
                'verbose_name': 'KPI do Exercício',
                'verbose_name_plural': 'KPIs dos Exercícios',
            },
        ),
        migrations.CreateModel(
            name='HistoricoExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=255, verbose_name='Ação Realizada')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição da Mudança')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='processes.executacaoprocesso', verbose_name='Execução')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Execução',
                'verbose_name_plural': 'Históricos de Execução',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='AcaoCorretiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('correcao', 'Correção'), ('prevencao', 'Prevenção')], max_length=50, verbose_name='Tipo de Ação')),
                ('descricao', models.TextField(verbose_name='Descrição da Ação')),
                ('data_prevista', models.DateField(verbose_name='Data Prevista de Conclusão')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data Real de Conclusão')),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('em_execucao', 'Em Execução'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='planejada', max_length=20, verbose_name='Status')),
                ('resultado', models.TextField(blank=True, verbose_name='Resultado da Implementação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('nc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes_corretivas', to='processes.naoconformidade', verbose_name='Não Conformidade')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes_corretivas_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Ação Corretiva (CAPA)',
                'verbose_name_plural': 'Ações Corretivas (CAPA)',
                'ordering': ['data_prevista'],
            },
        ),
        migrations.CreateModel(
            name='ExecucaoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluida', models.BooleanField(default=False, verbose_name='Concluída')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações da Etapa')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.etapaprocesso', verbose_name='Etapa')),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_executadas', to='processes.executacaoprocesso', verbose_name='Execução do Processo')),
            ],
            options={
                'verbose_name': 'Execução de Etapa',
                'verbose_name_plural': 'Execuções de Etapasscii',
                'ordering': ['etapa__ordem'],
                'unique_together': {('execucao', 'etapa')},
            },
        ),
    ]
