# Generated by Django 4.2 on 2026-02-10 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brewery', '0001_initial'),
        ('processes', '0002_executacaoprocesso_pontocriticohaccp_registrohaccp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Meta')),
                ('tipo', models.CharField(choices=[('lucro', 'Lucro Alvo'), ('producao', 'Meta de Produção'), ('orcamento', 'Orçamento'), ('qualidade', 'Meta de Qualidade')], max_length=50, verbose_name='Tipo de Meta')),
                ('valor_meta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da Meta')),
                ('valor_atual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Atual')),
                ('unidade', models.CharField(default='R$', max_length=50, verbose_name='Unidade (R$, kg, %, etc)')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Término')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cervejaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='brewery.brewery', verbose_name='Cervejaria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
